API叩いてメンテ日を取得。それをシートに記録する。
HikaruKubota/logres_gas_schedule pull request #10
Opened 2024-02-29 11:59 UTC by takkar-eq

## commonにAPIを叩いてreturnするコードを追加
- APIを叩いてメンテ告知日とメンテ日をjson形式で取得
- メンテ日は年が書いてないので告知日を元に年を推測するコードを追加
- Dateオブジェクトにしてメンテ日を返す

## cronにシートにメンテ日を記録するコードを追加
- メンテ日をcommonのメソッドから受け取る
- メンテ日記録用シートから対象範囲を取得
- そのメンテ日が未記録状態なら記録

2024-02-29 12:10 UTC, HikaruKubota requested changes

2024-02-29 14:50 UTC, HikaruKubota requested changes

2024-02-29 14:50 UTC, HikaruKubota commented on src/common.js
> +      const response = UrlFetchApp.fetch(PropertiesService.getScriptProperties().getProperty('getMaintenanceDateAPI'));
命名がおかしい
プロパティの名前にgetを付けるのは変。

2024-02-29 14:59 UTC, HikaruKubota requested changes

2024-02-29 15:13 UTC, HikaruKubota commented on src/common.js
> +      const response = UrlFetchApp.fetch("https://asia-northeast1-tonal-asset-415520.cloudfunctions.net/logres_scraping");
このURLは生成しなおしてるので大丈夫。

2024-02-29 15:32 UTC, takkar-eq commented on src/common.js
> +      let maintenanceInfo = [new Date(jsonData.notice_date.split(/[年月日]/)), new Date(jsonData.maintenance_date)];
DateObjectを作るならnew Dateなのかなと思ってやりました。
特に深い考えはないのでnewは消すべきですかね？

2024-03-01 11:59 UTC, HikaruKubota requested changes

2024-03-01 11:59 UTC, HikaruKubota commented on src/common.js
> +      if(today.getMonth() == 12 && maintenanceDate == 1){
===って使えなかったっけ？

2024-03-01 11:59 UTC, HikaruKubota commented on src/common.js
> +      if(today.getMonth() == 12 && maintenanceDate == 1){
どっちでも良いけど、可能なら===が良い。

2024-03-01 11:59 UTC, HikaruKubota commented on src/cron.js
>    }
ここの判定要らない。
同じ日を取得したとしても同じ日に上書きしたら一緒だし、
日が違うなら違う日で更新するのが正解だし

つまりどのみちsetValueしていい
判定が不要

2024-03-01 12:04 UTC, takkar-eq commented on src/common.js
> +      if(today.getMonth() == 12 && maintenanceDate == 1){
===使える！
ただ厳しく見たせいでif文通ってほしいのに通らない事があると嫌だなと思って==にしてみた感じ
とりあえず===に修正します！

2024-03-01 12:05 UTC, takkar-eq commented on src/cron.js
>    }
あら、りょーかい！

2024-03-01 16:36 UTC, HikaruKubota requested changes

2024-03-01 16:36 UTC, HikaruKubota commented on src/common.js
> +      if(today.getMonth() == 12 && maintenanceDate == 1){
基本===だなー。
その理屈だと動いてほしくない時に動いちゃうこともあるから。

2024-03-01 16:36 UTC, HikaruKubota commented on src/cron.js
> +  }
ここ全部要らんくない・・？

`sheet.getRange(2, 1).setValue(maintenanceDate);`

だけで良いと思うんだけど

2024-03-02 03:36 UTC, HikaruKubota approved these changes
特に問題ないと思う。

2024-03-15 05:07 UTC, merged